# Generated by Django 5.0 on 2024-01-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_chapter_href_novel_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='crawled_novel_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='novel_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='chapter_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='crawled_chapter_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='is_crawled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
